CREATE TABLE IF NOT EXISTS `User` (
	`id` BIGINT NOT NULL AUTO_INCREMENT UNIQUE,
	`username` TEXT(65535) NOT NULL,
	`password` TEXT(65535) NOT NULL,
	`status` TEXT(65535) NOT NULL,
	PRIMARY KEY(`id`)
);


CREATE TABLE IF NOT EXISTS `Role` (
	`id` BIGINT NOT NULL AUTO_INCREMENT UNIQUE,
	`role_name` TEXT(65535) NOT NULL,
	`role_code` TEXT(65535) NOT NULL,
	PRIMARY KEY(`id`)
);


CREATE TABLE IF NOT EXISTS `User_Role` (
	`id` BIGINT NOT NULL AUTO_INCREMENT UNIQUE,
	`role_id` BIGINT NOT NULL,
	`user_id` BIGINT NOT NULL,
	PRIMARY KEY(`id`)
);


CREATE TABLE IF NOT EXISTS `Doctor` (
	`id` BIGINT NOT NULL AUTO_INCREMENT UNIQUE,
	`user_id` BIGINT NOT NULL,
	`clinic_id` BIGINT NOT NULL,
	`specialization` TEXT(65535) NOT NULL,
	`fullname` TEXT(65535) NOT NULL,
	`phone` TEXT(65535),
	`email` TEXT(65535),
	`status` TEXT(65535),
	`image_url` TEXT(65535),
	PRIMARY KEY(`id`)
);


CREATE TABLE IF NOT EXISTS `Patient` (
	`id` BIGINT NOT NULL AUTO_INCREMENT UNIQUE,
	`user_id` BIGINT NOT NULL,
	`fullname` TEXT(65535) NOT NULL,
	`email` TEXT(65535),
	`gender` TEXT(65535) NOT NULL,
	`phone` TEXT(65535) NOT NULL,
	PRIMARY KEY(`id`)
);


CREATE TABLE IF NOT EXISTS `Appointment` (
	`id` BIGINT NOT NULL AUTO_INCREMENT UNIQUE,
	`doctor_id` BIGINT NOT NULL,
	`patient_id` BIGINT NOT NULL,
	`clinic_id` BIGINT NOT NULL,
	`time_slot_id` BIGINT NOT NULL,
	`note` TEXT(65535),
	PRIMARY KEY(`id`)
);


CREATE TABLE IF NOT EXISTS `Service` (
	`id` BIGINT NOT NULL AUTO_INCREMENT UNIQUE,
	`name` TEXT(65535) NOT NULL,
	`description` TEXT(65535),
	`price` DOUBLE,
	PRIMARY KEY(`id`)
);


CREATE TABLE IF NOT EXISTS `Appointment_Service` (
	`id` BIGINT NOT NULL AUTO_INCREMENT UNIQUE,
	`appointment_id` BIGINT NOT NULL,
	`service_id` BIGINT NOT NULL,
	PRIMARY KEY(`id`)
);


CREATE TABLE IF NOT EXISTS `Payment` (
	`id` BIGINT NOT NULL AUTO_INCREMENT UNIQUE,
	`appointment_id` BIGINT NOT NULL,
	`amount` BIGINT NOT NULL,
	`status` TEXT(65535) NOT NULL,
	PRIMARY KEY(`id`)
);


CREATE INDEX `Payment_index_0`
ON `Payment` ();
CREATE TABLE IF NOT EXISTS `Clinic` (
	`id` BIGINT NOT NULL AUTO_INCREMENT UNIQUE,
	`name` TEXT(65535) NOT NULL,
	`city` ENUM(),
	`phoneNumber` TEXT(65535),
	`email` TEXT(65535),
	`description` TEXT(65535),
	PRIMARY KEY(`id`)
);


CREATE INDEX `Clinic_index_0`
ON `Clinic` ();
CREATE TABLE IF NOT EXISTS `Time_Slot` (
	`id` BIGINT NOT NULL AUTO_INCREMENT UNIQUE,
	`start_time` DATETIME,
	`end_time` DATETIME,
	`description` TEXT(65535),
	PRIMARY KEY(`id`)
);


ALTER TABLE `Role`
ADD FOREIGN KEY(`id`) REFERENCES `User_Role`(`role_id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `User`
ADD FOREIGN KEY(`id`) REFERENCES `User_Role`(`user_id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `Doctor`
ADD FOREIGN KEY(`clinic_id`) REFERENCES `Clinic`(`id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `User`
ADD FOREIGN KEY(`id`) REFERENCES `Doctor`(`user_id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `Patient`
ADD FOREIGN KEY(`id`) REFERENCES `User`(`id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `Appointment`
ADD FOREIGN KEY(`doctor_id`) REFERENCES `Doctor`(`id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `Appointment`
ADD FOREIGN KEY(`patient_id`) REFERENCES `Patient`(`id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `Appointment_Service`
ADD FOREIGN KEY(`appointment_id`) REFERENCES `Appointment`(`id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `Service`
ADD FOREIGN KEY(`id`) REFERENCES `Appointment_Service`(`service_id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `Payment`
ADD FOREIGN KEY(`appointment_id`) REFERENCES `Appointment`(`id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;
ALTER TABLE `Time_Slot`
ADD FOREIGN KEY(`id`) REFERENCES `Appointment`(`time_slot_id`)
ON UPDATE NO ACTION ON DELETE NO ACTION;